# Generated by Django 4.0.4 on 2023-12-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wordentry_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='langNames',
            field=models.CharField(default='xd', max_length=64),
            preserve_default=False,
        ),
    ]
