# Generated by Django 4.2.7 on 2024-01-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_language_langnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='flag',
            field=models.CharField(default='', max_length=10),
        ),
    ]
