# Generated by Django 4.2.7 on 2024-01-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_language_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.CharField(default='', max_length=2),
        ),
    ]
