# Generated by Django 4.0.4 on 2024-03-16 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_vocabrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VocabRecord',
            new_name='WordRecord',
        ),
    ]
