# Generated by Django 4.0.4 on 2024-04-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_vocabrecord_wordrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='language',
            name='langNames',
        ),
    ]
