# Generated by Django 5.1 on 2024-08-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_language_flag_remove_language_langnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordentry',
            name='first_language',
        ),
        migrations.RemoveField(
            model_name='wordentry',
            name='second_language',
        ),
        migrations.RemoveField(
            model_name='wordrecord',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='wordrecord',
            name='count',
        ),
        migrations.AddField(
            model_name='wordrecord',
            name='one_of_three_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordrecord',
            name='one_of_three_count',
            field=models.IntegerField(default=0),
        ),
    ]
