# Generated by Django 4.2.7 on 2024-08-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_vocabularysetrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordrecord',
            old_name='one_of_three_correct',
            new_name='one_of_three_score',
        ),
        migrations.RenameField(
            model_name='wordrecord',
            old_name='one_of_three_count',
            new_name='one_of_three_streak',
        ),
    ]
