# Generated by Django 4.2.7 on 2024-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_vocabularysetrecord_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularysetrecord',
            name='mode',
            field=models.CharField(choices=[('OOT', 'One Of Three'), ('WTA', 'Write The Answer')], default='OOT', max_length=16),
        ),
    ]
