# Generated by Django 4.2.7 on 2024-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_vocabularysetrecord_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrecord',
            name='write_the_answer_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordrecord',
            name='write_the_answer_streak',
            field=models.IntegerField(default=0),
        ),
    ]
