# Generated by Django 4.2.7 on 2024-09-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_vocabularyuserrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularyuserrelationship',
            name='rating',
        ),
    ]
