# Generated by Django 4.2.7 on 2024-10-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_second_wordentry_translation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularyset',
            old_name='first_language',
            new_name='language',
        ),
    ]
