# Generated by Django 5.1.1 on 2025-04-19 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('alpha2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularySetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('fa_icon', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.language')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabularysetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularySetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('0', 'One Of Three'), ('1', 'Write The Answer'), ('2', 'Flashcards'), ('3', 'Draw Characters')], default='0', max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabularyset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyUserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabularyset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('phonetic', models.CharField(max_length=64)),
                ('translation', models.CharField(max_length=64)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vocabularyset',
            name='vocabulary',
            field=models.ManyToManyField(to='vocabulary.wordentry'),
        ),
        migrations.CreateModel(
            name='WordRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_of_three_score', models.IntegerField(default=0)),
                ('one_of_three_streak', models.IntegerField(default=0)),
                ('write_the_answer_score', models.IntegerField(default=0)),
                ('write_the_answer_streak', models.IntegerField(default=0)),
                ('draw_character_score', models.IntegerField(default=0)),
                ('draw_character_streak', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.wordentry')),
            ],
        ),
    ]
